import { Link, Navigate, useParams } from "react-router-dom";
import { PRACTICE_STACK, PROJECTS } from "../data/projects";
import { useLiveStats } from "../lib/useLiveStats";
import { Page } from "./Shell";
import { Reveal } from "./Reveal";
import { LiveValue, SectionHeading, StatGrid, Tags } from "./Parts";
import styles from "./ProjectDetail.module.css";
import { usePageMeta } from "../lib/usePageMeta";
import { ROUTE_META } from "../data/meta";

/**
 * One project, in full. The index carries four hooks; the write-up, the four
 * strata, the build record and the live activity all live here.
 */
export default function ProjectDetail() {
  const { slug } = useParams<{ slug: string }>();
  const project = PROJECTS.find((p) => p.slug === slug);
  const record = project?.buildRecord;

  // Every hook runs on every render, before the guard below — React matches
  // hooks by call order, so none of them may sit behind a conditional return.
  const stats = useLiveStats(project?.repo);

  // Runs unconditionally, before the guard below, like every other hook here.
  usePageMeta({
    title: project?.name ?? "Projects",
    description: project?.hook ?? ROUTE_META.home.description,
  });

  if (!project) return <Navigate to="/" replace />;

  return (
    <Page>
      <Reveal as="header" className={styles.head}>
        <Link className={styles.back} to="/">
          <span aria-hidden="true">←</span> Projects
        </Link>
        <h1 className={styles.title}>{project.name}</h1>
        <Tags items={project.classification} />
      </Reveal>

      <section className={styles.section}>
        <SectionHeading title="Overview" />
        <dl className={styles.overview}>
          <div className={styles.entry}>
            <dt className={styles.entryKey}>Problem</dt>
            <dd className={styles.entryValue}>{project.problem}</dd>
          </div>
          <div className={styles.entry}>
            <dt className={styles.entryKey}>Approach</dt>
            <dd className={styles.entryValue}>{project.approach}</dd>
          </div>
          <div className={styles.entry}>
            <dt className={styles.entryKey}>Result</dt>
            <dd className={styles.entryValue}>{project.outcome}</dd>
          </div>
        </dl>
      </section>

      <section className={styles.section}>
        <SectionHeading title="Stack" meta="4 layers" />
        {/* A description list, because these are label-and-value pairs: a
            screen reader announces "Interface, Discord slash commands" as one
            unit. */}
        <dl className={styles.strata}>
          {project.layers.map((layer) => {
            const generic = PRACTICE_STACK.find(
              (stratum) => stratum.role === layer.role,
            )?.part;

            return (
              <div key={layer.role} className={styles.stratum}>
                <dt className={styles.stratumRole}>
                  {layer.role.charAt(0) + layer.role.slice(1).toLowerCase()}
                </dt>
                <dd className={styles.stratumPart}>
                  {layer.part}
                  {generic ? (
                    <span className={styles.stratumGeneric}>{generic}</span>
                  ) : null}
                </dd>
              </div>
            );
          })}
        </dl>
      </section>

      {/* Only projects that have actually been analysed carry a build record. */}
      {record ? (
        <section className={styles.section}>
          <SectionHeading title="How it was built" meta={record.window} />

          <p className={styles.note}>
            Generated by {record.source} from this repository&rsquo;s Claude
            Code session logs: an outside read of how the project was built,
            not a self-assessment. These figures are a dated snapshot, not live
            data.
          </p>

          <StatGrid
            items={[
              { label: "Sessions", value: record.sessions },
              { label: "Hours", value: record.hours },
              {
                label: "Lines shipped",
                value: record.lines.toLocaleString("en-US"),
              },
              { label: "Commits", value: record.commits },
              { label: "Longest session", value: record.longestSession },
            ]}
          />

          <div className={styles.style}>
            <h3 className={styles.styleName}>{record.style}</h3>
            <p className={styles.styleNote}>{record.styleNote}</p>
            <ul className={styles.strengths}>
              {record.strengths.map((strength) => (
                <li key={strength} className={styles.strength}>
                  {strength}
                </li>
              ))}
            </ul>
            <a className={styles.quiet} href={record.url}>
              Read the full report
            </a>
          </div>
        </section>
      ) : null}

      <section className={styles.section}>
        <SectionHeading title="Activity" meta="Live from GitHub" />

        <StatGrid
          items={[
            {
              label: "Commits",
              value: (
                <LiveValue stats={stats} select={(d) => String(d.commits)} />
              ),
            },
            {
              label: "Last push",
              value: <LiveValue stats={stats} select={(d) => d.lastPush} />,
            },
            {
              label: "Languages",
              value: (
                <LiveValue
                  stats={stats}
                  select={(d) =>
                    d.languages.map(([name]) => name).join(" · ") || "None listed"
                  }
                />
              ),
            },
          ]}
        />

        <a
          className={styles.quiet}
          href={`https://github.com/${project.repo}`}
        >
          Open {project.repo}
        </a>
      </section>
    </Page>
  );
}
