import { Link, Navigate, useParams } from "react-router-dom";
import { Badges } from "../components/Badges";
import { LiveValue } from "../components/LiveValue";
import { PixelSprite } from "../components/PixelSprite";
import { Banner, Screen } from "../components/Screen";
import { PRACTICE_STACK, PROJECTS } from "../data/projects";
import { useLiveStats } from "../lib/useLiveStats";
import styles from "./ProjectDetail.module.css";
import { usePageMeta } from "../lib/usePageMeta";
import { ROUTE_META } from "../data/meta";

/**
 * One unit, in full. The roster shows four hooks; this is where the log,
 * the four strata and the live telemetry actually live.
 */
export default function ProjectDetail() {
  const { slug } = useParams<{ slug: string }>();
  const project = PROJECTS.find((p) => p.slug === slug);
  const record = project?.buildRecord;

  // Every hook runs on every render, before the guard below — React matches
  // hooks by call order, so none of them may sit behind a conditional return.
  const stats = useLiveStats(project?.repo);

  // Runs unconditionally, before the guard below, like every other hook here.
  usePageMeta({
    title: project?.name ?? "Projects",
    description: project?.hook ?? ROUTE_META.home.description,
  });

  if (!project) return <Navigate to="/" replace />;

  return (
    <Screen>
      <Link className={styles.back} to="/">
        &larr; Roster
      </Link>

      <section className={styles.plate}>
        <header className={styles.head}>
          <div className={styles.portrait}>
            <PixelSprite sprite={project.sprite} size={140} />
          </div>

          <div className={styles.identity}>
            <span className={styles.sheet}>Sheet {project.sheet}</span>
            <h1 className={styles.name}>{project.name}</h1>
            <Badges classification={project.classification} />
          </div>
        </header>

        <div className={styles.log}>
          <p className={styles.logEntry}>
            <span className={styles.logKey}>PROBLEM</span>
            {project.problem}
          </p>
          <p className={styles.logEntry}>
            <span className={styles.logKey}>METHOD</span>
            {project.approach}
          </p>
          <p className={styles.logEntry}>
            <span className={styles.logKey}>RESULT</span>
            {project.outcome}
          </p>
        </div>
      </section>

      <Banner title="STACK" count="4 strata" />

      {/* A description list, because these are label-and-value pairs: a screen
          reader announces "INTERFACE, Discord slash commands" as one unit. */}
      <dl className={styles.strata}>
        {project.layers.map((layer) => {
          const generic = PRACTICE_STACK.find(
            (stratum) => stratum.role === layer.role,
          )?.part;

          return (
            <div key={layer.role} className={styles.layer}>
              <dt className={styles.layerRole}>{layer.role}</dt>
              <dd className={styles.layerPart}>
                {layer.part}
                {generic ? (
                  <span className={styles.layerGeneric}>{generic}</span>
                ) : null}
              </dd>
            </div>
          );
        })}
      </dl>

      {/* Only units that have actually been analysed carry a build record. */}
      {record ? (
        <>
          <Banner title="BUILD RECORD" count={record.window} />

          <section className={styles.record}>
            <p className={styles.recordSource}>
              Generated by {record.source} from this repository&rsquo;s Claude
              Code session logs — an outside read of how the unit was built,
              not a self-assessment.
            </p>

            <div className={styles.stats}>
              <div className={styles.stat}>
                <span className={styles.statLabel}>Sessions</span>
                <span className={styles.statValue}>{record.sessions}</span>
              </div>
              <div className={styles.stat}>
                <span className={styles.statLabel}>Hours</span>
                <span className={styles.statValue}>{record.hours}</span>
              </div>
              <div className={styles.stat}>
                <span className={styles.statLabel}>Lines shipped</span>
                <span className={styles.statValue}>
                  {record.lines.toLocaleString("en-US")}
                </span>
              </div>
              <div className={styles.stat}>
                <span className={styles.statLabel}>Commits</span>
                <span className={styles.statValue}>{record.commits}</span>
              </div>
              <div className={styles.stat}>
                <span className={styles.statLabel}>Longest session</span>
                <span className={styles.statValue}>
                  {record.longestSession}
                </span>
              </div>
            </div>

            <div className={styles.styleBlock}>
              <span className={styles.statLabel}>Working style</span>
              <p className={styles.styleName}>{record.style}</p>
              <p className={styles.styleNote}>{record.styleNote}</p>
            </div>

            <ul className={styles.strengths}>
              {record.strengths.map((strength) => (
                <li key={strength} className={styles.strength}>
                  {strength}
                </li>
              ))}
            </ul>

            <a className={styles.open} href={record.url}>
              Full report
            </a>
          </section>
        </>
      ) : null}

      <Banner title="TELEMETRY" count="Live from GitHub" />

      <div className={styles.telemetry}>
        <div className={styles.stats}>
          <div className={styles.stat}>
            <span className={styles.statLabel}>Commits</span>
            <span className={styles.statValue}>
              <LiveValue stats={stats} select={(d) => String(d.commits)} />
            </span>
          </div>

          <div className={styles.stat}>
            <span className={styles.statLabel}>Last push</span>
            <span className={styles.statValue}>
              <LiveValue stats={stats} select={(d) => d.lastPush} />
            </span>
          </div>

          <div className={styles.stat}>
            <span className={styles.statLabel}>Languages</span>
            <span className={styles.statValue}>
              <LiveValue
                stats={stats}
                select={(d) =>
                  d.languages.map(([name]) => name).join(" · ") || "—"
                }
              />
            </span>
          </div>
        </div>

        <a className={styles.open} href={`https://github.com/${project.repo}`}>
          Open repo
        </a>
      </div>
    </Screen>
  );
}
